import { FormEvent, useMemo, useState } from 'react';
import { ArrowLeft, CalendarDays, ChevronRight, Compass, Flame, MessageCircle, Plus, Send, Users } from 'lucide-react';

export type RoomId = 'createurs' | 'food' | 'business' | 'music' | 'sport';
type Room = { id: RoomId; emoji: string; name: string; subtitle: string; members: string; color: string; prompt: string; event: string };
type RoomPost = { text: string; topic: string };
export const AXORA_ROOMS: Room[] = [
  { id: 'createurs', emoji: '🎨', name: 'Créateurs Kinshasa', subtitle: 'Design, photo & projets', members: '2,4 k membres', color: 'from-[#FF2D55]/15 to-[#FF2D55]/[0.03]', prompt: 'Montre une création dont tu es fier cette semaine.', event: 'Pop Créateurs · aujourd’hui, 19:30' },
  { id: 'food', emoji: '🍲', name: 'Food & sorties', subtitle: 'Bonnes adresses et idées', members: '1,8 k membres', color: 'from-[#FF2D55]/12 to-[#FF2D55]/[0.02]', prompt: 'Quelle adresse mérite vraiment d’être découverte ?', event: 'Sortie découverte · samedi, 16:00' },
  { id: 'business', emoji: '💼', name: 'Business Kinshasa', subtitle: 'Idées, opportunités & réseau', members: '3,1 k membres', color: 'from-[#FF2D55]/10 to-[#FF2D55]/[0.02]', prompt: 'Quelle idée veux-tu faire avancer cette semaine ?', event: 'Pop Business · ce soir, 20:30' },
  { id: 'music', emoji: '🎵', name: 'Musique & danse', subtitle: 'Sons, artistes & talents', members: '4,7 k membres', color: 'from-[#FF2D55]/14 to-[#FF2D55]/[0.03]', prompt: 'Quel son résume ton humeur du jour ?', event: 'Open mic Axora · vendredi, 18:00' },
  { id: 'sport', emoji: '⚽', name: 'Sport & mouvements', subtitle: 'Matchs, équipes & défis', members: '2,9 k membres', color: 'from-[#FF2D55]/10 to-[#FF2D55]/[0.02]', prompt: 'Qui est partant pour une activité ce week-end ?', event: 'Foot entre membres · dimanche, 09:00' },
];
const TOPICS = ['Général', 'Questions', 'Conseils', 'Événements', 'Projets'];

export function RoomsShelf({ onOpen }: { onOpen: (id: RoomId) => void }) {
  return <section aria-labelledby="rooms-heading" className="px-3 sm:px-4 max-w-5xl mx-auto"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#FF2D55]">Communautés</p><h2 id="rooms-heading" className="mt-1 text-lg font-black">Trouve ta Room</h2></div><button type="button" onClick={() => onOpen('createurs')} className="inline-flex items-center gap-1 text-xs font-black text-[#FF2D55]">Tout voir <ChevronRight className="h-4 w-4" /></button></div><div className="-mx-3 flex gap-3 overflow-x-auto px-3 pb-1 no-scrollbar sm:-mx-4 sm:px-4">{AXORA_ROOMS.map(room => <button key={room.id} type="button" onClick={() => onOpen(room.id)} className={`w-40 shrink-0 rounded-2xl border border-[var(--axo-border)] bg-gradient-to-br ${room.color} p-3 text-left shadow-sm`}><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#FF2D55]/10 text-xl">{room.emoji}</span><strong className="mt-3 block truncate text-xs">{room.name}</strong><span className="mt-1 block truncate text-[10px] text-[var(--axo-text-muted)]">{room.members}</span></button>)}</div></section>;
}

export default function AxoraRooms({ selectedId, onBack, onOpenMessages, onOpenPop }: { selectedId: RoomId; onBack: () => void; onOpenMessages: () => void; onOpenPop: () => void }) {
  const [roomId, setRoomId] = useState<RoomId>(selectedId); const [joined, setJoined] = useState<Set<RoomId>>(() => new Set([selectedId])); const [tab, setTab] = useState<'feed' | 'members' | 'agenda'>('feed'); const [topic, setTopic] = useState(TOPICS[0]); const [draft, setDraft] = useState(''); const [posts, setPosts] = useState<RoomPost[]>([]); const [popTitle, setPopTitle] = useState(''); const [roomPop, setRoomPop] = useState<string | null>(null);
  const room = useMemo(() => AXORA_ROOMS.find(item => item.id === roomId)!, [roomId]);
  const publish = (e: FormEvent) => { e.preventDefault(); if (!draft.trim()) return; setPosts(p => [{ text: draft.trim(), topic }, ...p]); setDraft(''); };
  const choose = (id: RoomId) => { setRoomId(id); setTab('feed'); setTopic(TOPICS[0]); };
  return <section className="min-h-full bg-[var(--axo-bg)] text-[var(--axo-text)]"><header className="sticky top-0 z-20 border-b border-[var(--axo-border)] bg-[var(--axo-bg)]/95 px-4 py-3 backdrop-blur-md"><div className="mx-auto flex max-w-3xl items-center gap-3"><button type="button" onClick={onBack} className="rounded-xl p-2" aria-label="Retour"><ArrowLeft className="h-5 w-5" /></button><div><p className="text-[9px] font-black uppercase tracking-[0.18em] text-[#FF2D55]">Axora Rooms</p><h1 className="text-sm font-black">Tes communautés, au même endroit</h1></div></div></header><main className="mx-auto max-w-3xl space-y-5 px-4 py-5 pb-28">
    <div className="flex gap-2 overflow-x-auto pb-1 no-scrollbar">{AXORA_ROOMS.map(item => <button key={item.id} type="button" onClick={() => choose(item.id)} className={`shrink-0 rounded-full px-3 py-2 text-[11px] font-bold ${roomId === item.id ? 'bg-[#FF2D55] text-white' : 'border border-[var(--axo-border)] bg-[var(--axo-surface)]'}`}>{item.emoji} {item.name}</button>)}</div>
    <section className={`rounded-3xl border border-[var(--axo-border)] bg-gradient-to-br ${room.color} p-5`}><div className="flex items-start justify-between"><span className="text-4xl">{room.emoji}</span><button type="button" onClick={() => setJoined(current => { const next = new Set(current); next.has(roomId) ? next.delete(roomId) : next.add(roomId); return next; })} className="rounded-xl border border-[var(--axo-border)] bg-[var(--axo-surface)] px-4 py-2.5 text-xs font-black">{joined.has(roomId) ? 'Membre' : 'Rejoindre'}</button></div><h2 className="mt-4 text-2xl font-black">{room.name}</h2><p className="mt-1 text-sm text-[var(--axo-text-muted)]">{room.subtitle} · {room.members}</p><div className="mt-5 rounded-2xl border border-[var(--axo-border)] bg-[var(--axo-surface)]/75 p-3"><p className="text-[9px] font-black uppercase tracking-widest text-[#FF2D55]">Sujet du jour</p><p className="mt-1 text-sm font-bold">{room.prompt}</p></div></section>
    <div className="grid grid-cols-3 rounded-2xl bg-[var(--axo-surface-muted)] p-1" role="tablist">{([['feed', 'Discussions'], ['members', 'Membres'], ['agenda', 'Pop & agenda']] as const).map(([id, label]) => <button key={id} type="button" role="tab" onClick={() => setTab(id)} className={`rounded-xl px-1 py-2.5 text-[9px] font-black sm:text-[10px] ${tab === id ? 'bg-[var(--axo-surface)] text-[#FF2D55] shadow-sm' : 'text-[var(--axo-text-muted)]'}`}>{label}</button>)}</div>
    {tab === 'feed' && <><form onSubmit={publish} className="rounded-2xl border border-[var(--axo-border)] bg-[var(--axo-surface)] p-3"><div className="mb-3 flex gap-2 overflow-x-auto no-scrollbar">{TOPICS.map(item => <button key={item} type="button" onClick={() => setTopic(item)} className={`shrink-0 rounded-full px-3 py-1.5 text-[10px] font-black ${topic === item ? 'bg-[#FF2D55] text-white' : 'bg-[var(--axo-surface-muted)] text-[var(--axo-text-muted)]'}`}>{item}</button>)}</div><textarea value={draft} onChange={e => setDraft(e.target.value)} rows={2} maxLength={300} placeholder={`Lance une discussion dans ${room.name}…`} className="w-full resize-none bg-transparent text-sm outline-none" /><div className="mt-2 flex items-center justify-between border-t border-[var(--axo-border)] pt-2"><span className="text-[10px] font-bold text-[var(--axo-text-muted)]">{topic}</span><button type="submit" disabled={!draft.trim()} className="inline-flex items-center gap-1.5 rounded-xl bg-[#FF2D55] px-3 py-2 text-[10px] font-black text-white disabled:opacity-40"><Send className="h-3.5 w-3.5" />Publier</button></div></form>{posts.map((post, i) => <article key={`${post.text}-${i}`} className="rounded-2xl border border-[var(--axo-border)] bg-[var(--axo-surface)] p-4"><div className="flex justify-between"><p className="text-[10px] font-black text-[#FF2D55]">VOUS · À l’instant</p><span className="rounded-full bg-[#FF2D55]/10 px-2 py-1 text-[9px] font-black text-[#FF2D55]">{post.topic}</span></div><p className="mt-2 text-sm">{post.text}</p></article>)}<article className="rounded-2xl border border-[var(--axo-border)] bg-[var(--axo-surface)] p-4"><div className="flex items-center gap-3"><span className="rounded-xl bg-[#FF2D55]/10 p-2"><Compass className="h-4 w-4 text-[#FF2D55]" /></span><div><p className="text-xs font-black">Discussion populaire</p><p className="text-[10px] text-[var(--axo-text-muted)]">Maya K. · il y a 18 min</p></div></div><p className="mt-3 text-sm">Je partage mes meilleures découvertes ici : ça évite de chercher seul et ça donne envie de se retrouver.</p></article></>}
    {tab === 'members' && <section className="rounded-2xl border border-[var(--axo-border)] bg-[var(--axo-surface)] p-4"><div className="flex gap-3"><span className="rounded-xl bg-[#FF2D55]/10 p-2"><Users className="h-5 w-5 text-[#FF2D55]" /></span><div><h3 className="text-sm font-black">Des membres qui partagent ton intérêt</h3><p className="mt-1 text-xs text-[var(--axo-text-muted)]">Discute dans le chat de la communauté pour faire connaissance.</p></div></div><button type="button" onClick={onOpenMessages} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[var(--axo-surface-muted)] px-4 py-3 text-xs font-black"><MessageCircle className="h-4 w-4 text-[#FF2D55]" />Ouvrir le chat</button></section>}
    {tab === 'agenda' && <section className="space-y-4 rounded-2xl border border-[var(--axo-border)] bg-[var(--axo-surface)] p-4"><div className="flex gap-3"><span className="rounded-xl bg-[#FF2D55]/10 p-2"><CalendarDays className="h-5 w-5 text-[#FF2D55]" /></span><div><p className="text-[10px] font-black uppercase tracking-widest text-[#FF2D55]">Pop de la Room</p><h3 className="mt-1 text-sm font-black">{roomPop ?? room.event}</h3><p className="mt-1 text-xs text-[var(--axo-text-muted)]">Lance une session temporaire sur le sujet de ton choix, réservée aux membres de cette Room.</p></div></div><div className="flex gap-2"><input value={popTitle} onChange={e => setPopTitle(e.target.value)} maxLength={80} placeholder="Ex. Débat sur les projets locaux" className="min-w-0 flex-1 rounded-xl border border-[var(--axo-border)] bg-transparent px-3 py-2.5 text-xs outline-none" /><button type="button" onClick={() => { if (popTitle.trim()) { setRoomPop(popTitle.trim()); setPopTitle(''); } }} disabled={!popTitle.trim()} className="inline-flex items-center gap-1 rounded-xl bg-[var(--axo-surface-muted)] px-3 py-2 text-[10px] font-black disabled:opacity-40"><Plus className="h-3.5 w-3.5 text-[#FF2D55]" />Créer</button></div><button type="button" onClick={onOpenPop} className="inline-flex items-center gap-2 rounded-xl bg-[#FF2D55] px-4 py-3 text-xs font-black text-white"><Flame className="h-4 w-4" />Rejoindre les Pop Sessions</button></section>}
  </main></section>;
}
