import { useState } from 'react';
import { BookOpen, Code2, LockKeyhole, Sparkles } from 'lucide-react';
import AiDocumentation from './AiDocumentation';
import JetpackComposeShowcase from './JetpackComposeShowcase';
import type { ModerationRole } from './ModerationPanel';

export default function DeveloperCenter({ role }: { role: ModerationRole }) {
  const [section, setSection] = useState<'documentation' | 'design-system'>('documentation');
  const hasAccess = role === 'admin' || role === 'moderator';

  if (!hasAccess) return <section className="mt-4 rounded-2xl border border-violet-500/20 bg-violet-500/[0.04] p-4 text-left"><div className="flex gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-violet-500/10 text-violet-400"><LockKeyhole className="h-4 w-4" /></span><div><h3 className="text-xs font-black">Centre développeur</h3><p className="mt-1 text-[10px] leading-relaxed text-zinc-500">Documentation interne réservée aux rôles administrateur et modérateur.</p></div></div></section>;

  return <section className="mt-4 overflow-hidden rounded-2xl border border-violet-500/20 bg-[var(--axo-surface-strong)] text-[var(--axo-text)] shadow-xl shadow-violet-500/[0.03]"><header className="border-b border-[var(--axo-border)] p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-violet-500/15 text-violet-300"><Sparkles className="h-5 w-5" /></span><div><p className="text-[9px] font-black tracking-[0.2em] text-violet-300">INTERNE · {role.toUpperCase()}</p><h3 className="mt-1 text-sm font-black">Documentation & Design system</h3><p className="mt-1 text-[10px] text-zinc-400">Références produit et implémentation mobile Axora.</p></div></div><div role="tablist" aria-label="Sections développeur" className="mt-4 flex gap-2"><button type="button" role="tab" aria-selected={section === 'documentation'} onClick={() => setSection('documentation')} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-[10px] font-black ${section === 'documentation' ? 'bg-violet-500 text-white' : 'bg-[var(--axo-surface-muted)] text-[var(--axo-text-muted)] hover:text-[var(--axo-text)]'}`}><BookOpen className="h-3.5 w-3.5" />Documentation</button><button type="button" role="tab" aria-selected={section === 'design-system'} onClick={() => setSection('design-system')} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-[10px] font-black ${section === 'design-system' ? 'bg-violet-500 text-white' : 'bg-[var(--axo-surface-muted)] text-[var(--axo-text-muted)] hover:text-[var(--axo-text)]'}`}><Code2 className="h-3.5 w-3.5" />Design system Android</button></div></header><div className="max-h-[80dvh] overflow-y-auto p-4 sm:p-5">{section === 'documentation' ? <AiDocumentation /> : <JetpackComposeShowcase />}</div></section>;
}
