import { useState, type ReactNode } from 'react';
import { Bell, CircleSlash2, EyeOff, Flag, Globe2, MessageCircle, Shield, UserRoundPlus, UsersRound, Volume2, X } from 'lucide-react';
import HelpCenter from './HelpCenter';
import NotificationPreferences from './NotificationPreferences';
import InvitationsPanel from './InvitationsPanel';
import ArchivePanel from './ArchivePanel';
import AdvancedAccountPanel from './AdvancedAccountPanel';
import SystemStatusPanel from './SystemStatusPanel';
import BillingPanel from './BillingPanel';
import ProfileActivityWallet from './ProfileActivityWallet';

type ReportReason = 'Harcèlement' | 'Usurpation d’identité' | 'Contenu dangereux' | 'Spam' | 'Autre';
const people = [
  { id: 'lena', name: 'Lena X', username: '@lena_x' },
  { id: 'neon', name: 'Neon Vibe', username: '@neon_vibe' },
];

export default function GlobalSettingsPanel({ isDark, theme, setTheme }: { isDark: boolean; theme: 'dark' | 'light'; setTheme: (theme: 'dark' | 'light') => void }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('axo_language') || 'Français');
  const [prefs, setPrefs] = useState({ push: true, email: false, sound: true, reduced: false, contrast: false, messages: 'Abonnements', comments: 'Tout le monde', tags: 'Personne', stories: 'Amis', activity: 'Abonnements' });
  const [blocked, setBlocked] = useState<string[]>(['lena']);
  const [muted, setMuted] = useState<string[]>(['neon']);
  const [requests, setRequests] = useState(['Mila K.', 'Dorian M.']);
  const [reportOpen, setReportOpen] = useState(false);
  const [reason, setReason] = useState<ReportReason>('Harcèlement');
  const [description, setDescription] = useState('');
  const [reported, setReported] = useState(false);
  const panel = isDark ? 'border-white/5 bg-white/[0.015]' : 'border-slate-200 bg-slate-50';
  const toggle = (key: 'push' | 'email' | 'sound' | 'reduced' | 'contrast') => setPrefs(current => ({ ...current, [key]: !current[key] }));
  const select = (key: 'messages' | 'comments' | 'tags' | 'stories' | 'activity', value: string) => setPrefs(current => ({ ...current, [key]: value }));
  const setLanguageAndPersist = (value: string) => { setLanguage(value); localStorage.setItem('axo_language', value); };
  return <section className="space-y-4 border-t border-white/5 pt-6 text-left">
    <div><h3 className="text-[10px] font-black uppercase tracking-widest text-[#A855F7]">Centre de paramètres</h3><p className="mt-1 text-[11px] text-zinc-400">Préférences locales de cette maquette.</p></div>
    <div className={`rounded-2xl border p-4 ${panel}`}><h4 className="flex items-center gap-2 text-xs font-black"><Bell className="h-4 w-4 text-[#FF2D55]" />Notifications et langue</h4><div className="mt-3 space-y-2">{([['push', 'Notifications push'], ['email', 'Résumé e-mail'], ['sound', 'Sons de l’application']] as const).map(([key, label]) => <div key={key}><Switch label={label} checked={prefs[key]} onChange={() => toggle(key)} /></div>)}<label className="mt-3 block text-[10px] font-bold text-zinc-400">Langue<select value={language} onChange={event => setLanguageAndPersist(event.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-transparent px-3 py-2 text-xs outline-none"><option>Français</option><option>English</option><option>Lingala</option></select></label></div></div>
    <div className={`rounded-2xl border p-4 ${panel}`}><h4 className="flex items-center gap-2 text-xs font-black"><Globe2 className="h-4 w-4 text-cyan-400" />Apparence et accessibilité</h4><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => setTheme('light')} className={`rounded-xl border px-3 py-2 text-[10px] font-bold ${theme === 'light' ? 'border-cyan-400 text-cyan-500' : 'border-white/10'}`}>Clair</button><button type="button" onClick={() => setTheme('dark')} className={`rounded-xl border px-3 py-2 text-[10px] font-bold ${theme === 'dark' ? 'border-cyan-400 text-cyan-500' : 'border-white/10'}`}>Sombre</button></div><div className="mt-2 space-y-2"><Switch label="Réduire les animations" checked={prefs.reduced} onChange={() => toggle('reduced')} /><Switch label="Contraste renforcé" checked={prefs.contrast} onChange={() => toggle('contrast')} /></div></div>
    <div className={`rounded-2xl border p-4 ${panel}`}><h4 className="flex items-center gap-2 text-xs font-black"><Shield className="h-4 w-4 text-emerald-500" />Confidentialité</h4><p className="mt-1 text-[10px] leading-relaxed text-zinc-400">Définissez qui peut interagir avec votre compte.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><PrivacySelect label="Peut m’écrire" value={prefs.messages} options={['Tout le monde', 'Abonnements', 'Personne']} onChange={value => select('messages', value)} /><PrivacySelect label="Peut commenter" value={prefs.comments} options={['Tout le monde', 'Abonnements', 'Personne']} onChange={value => select('comments', value)} /><PrivacySelect label="Peut m’identifier" value={prefs.tags} options={['Tout le monde', 'Abonnements', 'Personne']} onChange={value => select('tags', value)} /><PrivacySelect label="Voit mes stories" value={prefs.stories} options={['Tout le monde', 'Amis', 'Personne']} onChange={value => select('stories', value)} /><PrivacySelect label="Voit mon activité" value={prefs.activity} options={['Tout le monde', 'Abonnements', 'Personne']} onChange={value => select('activity', value)} /></div></div>
    <div className={`rounded-2xl border p-4 ${panel}`}><h4 className="flex items-center gap-2 text-xs font-black"><UsersRound className="h-4 w-4 text-amber-500" />Relations et modération</h4><div className="mt-3 space-y-3"><PeopleGroup title="Utilisateurs bloqués" icon={<CircleSlash2 className="h-3.5 w-3.5 text-red-500" />} ids={blocked} action="Débloquer" onAction={id => setBlocked(current => current.filter(item => item !== id))} empty="Aucun utilisateur bloqué." /><PeopleGroup title="Comptes masqués" icon={<EyeOff className="h-3.5 w-3.5 text-zinc-500" />} ids={muted} action="Afficher" onAction={id => setMuted(current => current.filter(item => item !== id))} empty="Aucun compte masqué." /><div><p className="flex items-center gap-1 text-[10px] font-black"><UserRoundPlus className="h-3.5 w-3.5 text-emerald-500" />Demandes de suivi</p>{requests.length ? requests.map(name => <div key={name} className="mt-2 flex items-center justify-between rounded-xl border border-white/5 px-3 py-2 text-[10px]"><span className="font-bold">{name}</span><span className="flex gap-2"><button type="button" onClick={() => setRequests(current => current.filter(item => item !== name))} className="text-emerald-500">Accepter</button><button type="button" onClick={() => setRequests(current => current.filter(item => item !== name))} className="text-red-500">Refuser</button></span></div>) : <p className="mt-2 text-[10px] text-zinc-500">Aucune demande en attente.</p>}</div><button type="button" onClick={() => { setReportOpen(true); setReported(false); setDescription(''); }} className="flex w-full items-center justify-center gap-2 rounded-xl border border-red-500/30 bg-red-500/5 px-3 py-2.5 text-[10px] font-black text-red-500"><Flag className="h-3.5 w-3.5" />Signaler un contenu ou un compte</button></div></div>
    {reportOpen && <Dialog title="Signaler" onClose={() => setReportOpen(false)}>{reported ? <div className="space-y-3 text-center"><Flag className="mx-auto h-9 w-9 text-emerald-500" /><p>Merci. Votre signalement simulé a été enregistré.</p><button type="button" onClick={() => setReportOpen(false)} className="w-full rounded-xl bg-emerald-500 py-3 text-[10px] font-black text-zinc-950">Fermer</button></div> : <><p>Décrivez le problème. Aucun signalement n’est transmis dans cette version front-end.</p><label className="mt-4 block text-[10px] font-bold">Motif<select value={reason} onChange={event => setReason(event.target.value as ReportReason)} className="mt-1 w-full rounded-xl border border-white/10 bg-transparent px-3 py-2 text-xs">{(['Harcèlement', 'Usurpation d’identité', 'Contenu dangereux', 'Spam', 'Autre'] as ReportReason[]).map(item => <option key={item}>{item}</option>)}</select></label><label className="mt-3 block text-[10px] font-bold">Description<textarea value={description} onChange={event => setDescription(event.target.value)} rows={3} placeholder="Ajoutez des détails…" className="mt-1 w-full rounded-xl border border-white/10 bg-transparent p-3 text-xs" /></label><button type="button" disabled={!description.trim()} onClick={() => setReported(true)} className="mt-4 w-full rounded-xl bg-red-500 py-3 text-[10px] font-black text-white disabled:opacity-40">Envoyer le signalement</button></>}</Dialog>}
    <NotificationPreferences />
    <InvitationsPanel />
    <ArchivePanel />
    <AdvancedAccountPanel />
    <SystemStatusPanel />
    <BillingPanel />
    <ProfileActivityWallet />
    <HelpCenter />
  </section>;
}

function Switch({ label, checked, onChange }: { label: string; checked: boolean; onChange: () => void }) { return <button type="button" onClick={onChange} className="flex w-full items-center justify-between rounded-xl border border-white/5 px-3 py-2 text-left text-[10px] font-bold"><span>{label}</span><span className={`h-5 w-9 rounded-full p-0.5 transition ${checked ? 'bg-[#FF2D55]' : 'bg-zinc-600'}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${checked ? 'translate-x-4' : ''}`} /></span></button>; }
function PrivacySelect({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="block text-[10px] font-bold text-zinc-400">{label}<select value={value} onChange={event => onChange(event.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-transparent px-3 py-2 text-xs text-inherit">{options.map(option => <option key={option}>{option}</option>)}</select></label>; }
function PeopleGroup({ title, icon, ids, action, onAction, empty }: { title: string; icon: ReactNode; ids: string[]; action: string; onAction: (id: string) => void; empty: string }) { return <div><p className="flex items-center gap-1 text-[10px] font-black">{icon}{title}</p>{ids.length ? ids.map(id => { const person = people.find(item => item.id === id)!; return <div key={id} className="mt-2 flex items-center justify-between rounded-xl border border-white/5 px-3 py-2 text-[10px]"><span><b>{person.name}</b> <span className="text-zinc-500">{person.username}</span></span><button type="button" onClick={() => onAction(id)} className="font-bold text-cyan-400">{action}</button></div>; }) : <p className="mt-2 text-[10px] text-zinc-500">{empty}</p>}</div>; }
function Dialog({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/75 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-sm rounded-[28px] bg-zinc-900 p-6 text-white shadow-2xl"><div className="flex items-center justify-between"><h3 className="text-sm font-black">{title}</h3><button type="button" onClick={onClose} aria-label="Fermer"><X className="h-5 w-5" /></button></div><div className="mt-4 text-xs leading-relaxed text-zinc-300">{children}</div></div></div>; }
