import React, { ChangeEvent, useRef, useState } from 'react';
import { ArrowRight, Camera, Check, ChevronLeft, Globe, ImagePlus, Lock, Send, Sparkles, Type, Users, X } from 'lucide-react';
import { Story, AxoraNotification } from '../types';

interface StoryCreatorModalProps { showCreateStoryModal: boolean; setShowCreateStoryModal: (open: boolean) => void; currentUserAvatar: string; setStories: React.Dispatch<React.SetStateAction<Story[]>>; setCoins: React.Dispatch<React.SetStateAction<number>>; setNotifications: React.Dispatch<React.SetStateAction<AxoraNotification[]>>; setActiveStory: (story: Story | null) => void; }
const gradients = [{ id: 'rose', value: 'linear-gradient(145deg,#ff2d55,#8b1e73)' }, { id: 'ocean', value: 'linear-gradient(145deg,#1c8cff,#102a72)' }, { id: 'sun', value: 'linear-gradient(145deg,#ff9a1f,#e84428)' }, { id: 'night', value: 'linear-gradient(145deg,#302c63,#10121e)' }];
const cover = (color: string) => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><rect width="100%" height="100%" fill="${color.includes('#1c') ? '#1c8cff' : color.includes('#ff9') ? '#ff9a1f' : color.includes('#302') ? '#302c63' : '#ff2d55'}"/></svg>`)}`;

export default function StoryCreatorModal({ showCreateStoryModal, setShowCreateStoryModal, currentUserAvatar, setStories, setNotifications, setActiveStory }: StoryCreatorModalProps) {
  const gallery = useRef<HTMLInputElement>(null), camera = useRef<HTMLInputElement>(null), preview = useRef<HTMLDivElement>(null);
  const [step, setStep] = useState<'select'|'crop'|'edit'|'share'>('select'); const [image, setImage] = useState(''); const [caption, setCaption] = useState(''); const [gradient, setGradient] = useState(gradients[0]); const [scale, setScale] = useState(1); const [privateStory, setPrivateStory] = useState(false); const [position, setPosition] = useState({ x: 50, y: 72 });
  if (!showCreateStoryModal) return null;
  const pick = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file?.type.startsWith('image/')) return; setImage(URL.createObjectURL(file)); setScale(1); setStep('crop'); };
  const drag = (event: React.PointerEvent<HTMLParagraphElement>) => { const box = preview.current?.getBoundingClientRect(); if (!box) return; const clamp = (n:number) => Math.min(88, Math.max(12,n)); setPosition({x:clamp((event.clientX-box.left)/box.width*100), y:clamp((event.clientY-box.top)/box.height*100)}); };
  const publish = () => { const story: Story = { id:`story-${Date.now()}`, username:'Vous', avatar:currentUserAvatar, isSeen:false, mediaUrl:image || cover(gradient.value), caption, filter:'normal', font:'font-sans', captionColor:'#fff', auraLevel:0, isPrivate:privateStory, stickers:[], createdAt:Date.now(), expiresAt:Date.now()+86_400_000, views:[], responses:[] }; setStories(items=>[story,...items]); setNotifications(items=>[{id:`story-notif-${Date.now()}`,type:'system',title:'Story publiée',description:privateStory?'Visible uniquement par vos proches.':'Votre Story est maintenant visible.',timestamp:'À l’instant'},...items]); setShowCreateStoryModal(false); setActiveStory(story); };
  const back = () => setStep(step==='share'?'edit':step==='edit'?(image?'crop':'select'):'select');
  const Canvas = ({small=false}:{small?:boolean}) => <div ref={preview} className={`relative aspect-[9/16] overflow-hidden bg-zinc-950 ${small?'w-28 rounded-2xl':'h-full max-h-[72dvh] w-auto max-w-full sm:rounded-[28px]'}`} style={{background:image?'#111':gradient.value}}>{image&&<img src={image} alt="Aperçu Story" className="absolute inset-0 h-full w-full object-cover" style={{transform:`scale(${scale})`}}/>}<div className="absolute inset-0 bg-gradient-to-t from-black/55 via-transparent to-black/25"/><div className="absolute left-4 top-4 flex items-center gap-2 text-white"><img src={currentUserAvatar} alt="" className="h-8 w-8 rounded-full border border-white/50"/><b className="text-xs">Votre Story</b></div>{caption&&<p onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag(e)}} onPointerMove={e=>e.currentTarget.hasPointerCapture(e.pointerId)&&drag(e)} onPointerUp={e=>e.currentTarget.releasePointerCapture(e.pointerId)} className="absolute z-10 w-[82%] touch-none select-none text-center text-xl font-black leading-snug text-white drop-shadow-lg cursor-grab active:cursor-grabbing" style={{left:`${position.x}%`,top:`${position.y}%`,transform:'translate(-50%,-50%)'}}>{caption}</p>}<span className="absolute bottom-4 right-4 rounded-full bg-black/40 px-2 py-1 text-[10px] text-white">24 h</span></div>;
  const title = step==='select'?'Créer une Story':step==='crop'?'Ajuster':step==='edit'?'Modifier':'Partager';
  return <div className="fixed inset-0 z-[100] bg-[var(--axo-bg)] text-[var(--axo-text)]"><section className="flex h-[100dvh] flex-col overflow-hidden bg-[var(--axo-surface)]"><header className="flex items-center justify-between border-b border-[var(--axo-border)] px-4 pb-3 pt-[max(.9rem,env(safe-area-inset-top))]"><button type="button" onClick={step==='select'?undefined:back} className="flex h-10 w-10 items-center justify-center rounded-full hover:bg-[var(--axo-surface-muted)]" aria-label="Retour">{step!=='select'&&<ChevronLeft className="h-5 w-5"/>}</button><div className="text-center"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[var(--axo-accent)]">Story Axora</p><h2 className="text-sm font-black">{title}</h2></div><button type="button" onClick={()=>setShowCreateStoryModal(false)} className="flex h-10 w-10 items-center justify-center rounded-full hover:bg-[var(--axo-surface-muted)]" aria-label="Fermer"><X className="h-5 w-5"/></button></header>
  {step==='select'&&<main className="flex min-h-0 flex-1 flex-col"><div className="flex flex-1 flex-col items-center justify-center px-5 text-center"><span className="flex h-16 w-16 items-center justify-center rounded-3xl bg-[var(--axo-accent)]/10 text-[var(--axo-accent)]"><Sparkles className="h-8 w-8"/></span><h1 className="mt-5 text-2xl font-black">Partagez un instant</h1><p className="mt-2 text-sm text-[var(--axo-text-muted)]">Choisissez comment commencer votre Story.</p></div><div className="space-y-3 border-t border-[var(--axo-border)] p-4 pb-[max(1.25rem,env(safe-area-inset-bottom))]"><input ref={gallery} type="file" accept="image/*" onChange={pick} className="hidden"/><input ref={camera} type="file" accept="image/*" capture="environment" onChange={pick} className="hidden"/><button onClick={()=>gallery.current?.click()} className="flex min-h-16 w-full items-center gap-4 rounded-2xl bg-[var(--axo-accent)] px-5 text-left text-white"><ImagePlus className="h-6 w-6"/><span><b className="block text-sm">Choisir dans la galerie</b><small className="text-white/75">Photo depuis votre appareil</small></span><ArrowRight className="ml-auto"/></button><div className="grid grid-cols-2 gap-3"><button onClick={()=>camera.current?.click()} className="flex min-h-20 flex-col items-center justify-center gap-2 rounded-2xl border border-[var(--axo-border)] bg-[var(--axo-surface-muted)] text-xs font-black"><Camera className="text-[var(--axo-accent)]"/>Prendre une photo</button><button onClick={()=>{setImage('');setStep('edit')}} className="flex min-h-20 flex-col items-center justify-center gap-2 rounded-2xl border border-[var(--axo-border)] bg-[var(--axo-surface-muted)] text-xs font-black"><Type className="text-[var(--axo-accent)]"/>Créer avec du texte</button></div></div></main>}
  {step==='crop'&&<main className="flex min-h-0 flex-1 flex-col bg-zinc-950 text-white"><div className="flex min-h-0 flex-1 items-center justify-center overflow-hidden"><Canvas/></div><div className="border-t border-white/10 p-4 pb-[max(1.25rem,env(safe-area-inset-bottom))]"><input type="range" min="1" max="1.8" step=".01" value={scale} onChange={e=>setScale(Number(e.target.value))} className="w-full accent-[#ff2d55]"/><button onClick={()=>setStep('edit')} className="mt-4 flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[#ff2d55] text-xs font-black">Suivant <ArrowRight className="h-4 w-4"/></button></div></main>}
  {step==='edit'&&<main className="flex min-h-0 flex-1 flex-col bg-zinc-950 text-white"><div className="flex min-h-0 flex-1 items-center justify-center overflow-hidden"><Canvas/></div><div className="border-t border-white/10 p-4 pb-[max(1.25rem,env(safe-area-inset-bottom))]"><div className="flex gap-2">{gradients.map(item=><button key={item.id} onClick={()=>{setGradient(item);setImage('')}} className={`h-10 w-10 rounded-2xl border-2 ${gradient.id===item.id&&!image?'border-white':'border-transparent'}`} style={{background:item.value}}>{gradient.id===item.id&&!image&&<Check className="mx-auto h-4 w-4"/>}</button>)}</div><textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={160} rows={2} placeholder="Écrivez votre Story…" className="mt-3 w-full resize-none rounded-2xl bg-white/10 p-3 text-sm outline-none"/><p className="mt-1 text-[10px] text-zinc-400">Glissez le texte dans l’aperçu pour le placer.</p><button onClick={()=>setStep('share')} className="mt-3 flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[#ff2d55] text-xs font-black">Suivant <ArrowRight className="h-4 w-4"/></button></div></main>}
  {step==='share'&&<><main className="min-h-0 flex-1 overflow-y-auto p-5"><div className="mx-auto max-w-md"><div className="flex gap-4 rounded-3xl bg-[var(--axo-surface-muted)] p-3"><Canvas small/><div><h1 className="font-black">Prête à partager</h1><p className="mt-1 text-xs text-[var(--axo-text-muted)]">Votre Story disparaîtra après 24 h.</p></div></div><p className="mt-6 text-xs font-black">Audience</p><div className="mt-3 grid grid-cols-2 gap-3"><button onClick={()=>setPrivateStory(false)} className={`rounded-2xl border p-4 text-left ${!privateStory?'border-[var(--axo-accent)] bg-[var(--axo-accent)]/8':'border-[var(--axo-border)]'}`}><Globe className="text-[var(--axo-accent)]"/><b className="mt-3 block text-xs">Tout le monde</b></button><button onClick={()=>setPrivateStory(true)} className={`rounded-2xl border p-4 text-left ${privateStory?'border-[var(--axo-accent)] bg-[var(--axo-accent)]/8':'border-[var(--axo-border)]'}`}><Users className="text-[var(--axo-accent)]"/><b className="mt-3 block text-xs">Proches amis</b></button></div></div></main><footer className="border-t border-[var(--axo-border)] p-4 pb-[max(1rem,env(safe-area-inset-bottom))]"><button onClick={publish} className="mx-auto flex h-12 w-full max-w-md items-center justify-center gap-2 rounded-2xl bg-[var(--axo-accent)] text-xs font-black text-white"><Send className="h-4 w-4"/>Partager la Story</button><p className="mt-2 flex justify-center gap-1 text-[10px] text-[var(--axo-text-muted)]"><Lock className="h-3 w-3"/>Visible pendant 24 heures</p></footer></>}</section></div>;
}
